### ISSUE TITLE
dubbele .intro selector notDRY

### ISSUE THREAD

**Issue by tom-2810** [WesleySchorel/your-tribe-for-life-profile-card#5]
https://github.com/WesleySchorel/your-tribe-for-life-profile-card/blob/5a0cd44952000764188a6839d046e0ef3e995548/src/lib/slices/Intro/index.svelte#L29

**Comment by WesleySchorel** [comment]
Ik heb de css netter geschreven! Dankje ik had hier overheen gelezen :)
