### ISSUE TITLE
Alt uit slicemachine?

### ISSUE THREAD

**Issue by Tristandemuijnck** [WesleySchorel/your-tribe-for-life-profile-card#6]
https://github.com/WesleySchorel/your-tribe-for-life-profile-card/blob/5a0cd44952000764188a6839d046e0ef3e995548/src/lib/slices/Intro/index.svelte#L13

Als je een alt in slicemachine heb bijgevoegd, moet je deze ook nog toevoegen in je html code. Dit kun je doen op dezelfde manier als je andere content.

**Comment by WesleySchorel** [comment]
Ik heb een alt text toegevoegd, dankjewel voor deze toelichting!
